#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=../dev-lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/../dev-lib.sh"

if [[ $# -lt 1 ]]; then
  echo "Usage: ${DEV_CMD:-$0} <env-id>"
  exit 1
fi

work_id="$1"
if [[ -z "$work_id" ]]; then
  echo "Environment ID is required (example: dev or combat-rework)."
  exit 1
fi

repo_root="$REPO_ROOT"
generated_header="# Generated by ./tools/dev for DarkThrone worktree development."

hash_to_offset() {
  local hash
  hash="$(cksum <<<"$1" | awk '{print $1}')"
  echo $((hash % 10000 + 1))
}

port_in_use() {
  local port="$1"

  if command -v lsof >/dev/null 2>&1 && lsof -nP -iTCP:"${port}" -sTCP:LISTEN >/dev/null 2>&1; then
    return 0
  fi

  if command -v nc >/dev/null 2>&1 && nc -z 127.0.0.1 "${port}" >/dev/null 2>&1; then
    return 0
  fi

  if (echo >/dev/tcp/127.0.0.1/"${port}") >/dev/null 2>&1; then
    return 0
  fi

  return 1
}

ports_available() {
  local ports=("$@")
  local env_files=()
  while IFS= read -r env_file; do
    [[ -f "$env_file" ]] && env_files+=("$env_file")
  done < <(collect_env_files "$repo_root")

  for port in "${ports[@]}"; do
    if [[ "${#env_files[@]}" -gt 0 ]] && rg -q "=${port}$" "${env_files[@]}" 2>/dev/null; then
      return 1
    fi
    if port_in_use "$port"; then
      return 1
    fi
  done
  return 0
}

backup_env_file() {
  local file="$1"
  local backup="${file}.worktree-backup"

  if [[ -f "$file" && ! -f "$backup" ]] && ! grep -q '^# Generated by ./tools/dev' "$file"; then
    cp "$file" "$backup"
  fi
}

append_existing_env() {
  local source_file="$1"
  local key="$2"

  if [[ ! -f "$source_file" ]]; then
    return
  fi

  local value
  value="$(read_env_value "$source_file" "$key" || true)"
  if [[ -n "$value" ]]; then
    printf '%s=%s\n' "$key" "$value"
  fi
}

base_offset="$(hash_to_offset "$work_id")"
offset=""

base_api=52000
base_web=52100
base_site=52200
base_pg=54000

for i in $(seq 0 9999); do
  candidate=$(((base_offset + i - 1) % 10000 + 1))
  api_port=$((base_api + candidate))
  web_port=$((base_web + candidate))
  site_port=$((base_site + candidate))
  pg_port=$((base_pg + candidate))

  too_high=0
  for port in "$api_port" "$web_port" "$site_port" "$pg_port"; do
    if ((port > 65535)); then
      too_high=1
      break
    fi
  done

  if ((too_high == 1)); then
    continue
  fi

  if ports_available "$api_port" "$web_port" "$site_port" "$pg_port"; then
    offset="$candidate"
    break
  fi
done

if [[ -z "$offset" ]]; then
  echo "Unable to find an available port range. Remove old environments or stop services."
  exit 1
fi

data_root="${repo_root}/.data/${work_id}"
mkdir -p "${data_root}/postgres"

db_slug="$(slugify_lower "${work_id}" | tr '-' '_')"
if [[ -z "$db_slug" ]]; then
  echo "Environment ID produces an invalid database name. Use a different ID."
  exit 1
fi

db_name="darkthrone_${db_slug}"
compose_project="dt-$(slugify_lower "${work_id}")"
domain_base="${LOCAL_DOMAIN_BASE:-darkthrone.test}"
domain_port="${CADDY_HTTP_PORT:-8080}"
domain_slug="$(slugify_lower "${work_id}")"

web_domain="http://${domain_slug}.${domain_base}:${domain_port}"
api_domain="http://api.${domain_slug}.${domain_base}:${domain_port}"
site_domain="http://site.${domain_slug}.${domain_base}:${domain_port}"

cat > "${repo_root}/.env.dev" <<EOF
WORK_ID=${work_id}
DATA_ROOT=${data_root}
COMPOSE_PROJECT=${compose_project}

PG_PORT=${pg_port}
PG_DB=${db_name}
PG_USER=darkthrone
PG_PASSWORD=darkthrone

API_PORT=${api_port}
WEB_APP_PORT=${web_port}
WEBSITE_PORT=${site_port}
WEB_APP_PREVIEW_PORT=$((web_port + 1000))
WEBSITE_PREVIEW_PORT=$((site_port + 1000))

WEB_APP_URL=${web_domain}
API_URL=${api_domain}
WEBSITE_URL=${site_domain}
EOF

cp "${repo_root}/.env.dev" "${data_root}/.env.dev"

api_env="${repo_root}/apps/api/.env.local"
backup_env_file "$api_env"
{
  echo "${generated_header}"
  echo "API_PORT=${api_port}"
  echo "WEBAPP_ORIGIN=${web_domain}"
  echo "JWT_SECRET=darkthrone-local-${domain_slug}"
  echo "RDS_HOSTNAME=127.0.0.1"
  echo "RDS_PORT=${pg_port}"
  echo "RDS_USERNAME=darkthrone"
  echo "RDS_PASSWORD=darkthrone"
  echo "RDS_DB_NAME=${db_name}"
  echo "LOG_LEVEL=debug"
  append_existing_env "${api_env}.worktree-backup" "LOGTAIL_SOURCE_TOKEN"
  append_existing_env "${api_env}.worktree-backup" "EMAIL_FROM"
  append_existing_env "${api_env}.worktree-backup" "EMAIL_PASSWORD"
} > "$api_env"

api_test_env="${repo_root}/apps/api/.env.test.local"
backup_env_file "$api_test_env"
{
  echo "${generated_header}"
  echo "RDS_HOSTNAME=127.0.0.1"
  echo "RDS_PORT=${pg_port}"
  echo "RDS_USERNAME=darkthrone"
  echo "RDS_PASSWORD=darkthrone"
  echo "RDS_DB_NAME=${db_name}_test"
  echo "JWT_SECRET=darkthrone-test-${domain_slug}"
  echo "WEBAPP_ORIGIN=${web_domain}"
} > "$api_test_env"

web_env="${repo_root}/apps/web-app/.env.local"
backup_env_file "$web_env"
cat > "$web_env" <<EOF
${generated_header}
VITE_GAME_API_URL=${api_domain}
VITE_DEV_PORT=${web_port}
VITE_PREVIEW_PORT=$((web_port + 1000))
VITE_DEV_HOST=0.0.0.0
VITE_ALLOWED_HOSTS=.${domain_base},.darkthrone.local
EOF

site_env="${repo_root}/apps/website/.env.local"
backup_env_file "$site_env"
cat > "$site_env" <<EOF
${generated_header}
VITE_GAME_APP_URL=${web_domain}
VITE_DEV_PORT=${site_port}
VITE_PREVIEW_PORT=$((site_port + 1000))
VITE_DEV_HOST=0.0.0.0
VITE_ALLOWED_HOSTS=.${domain_base},.darkthrone.local
EOF

echo "Generated worktree environment for ${work_id}"
echo "  API:      ${api_domain}"
echo "  Web App:  ${web_domain}"
echo "  Website:  ${site_domain}"
echo "  Postgres: postgresql://darkthrone:darkthrone@localhost:${pg_port}/${db_name}"
