version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_dark_throne
    environment:
      POSTGRES_DB: ${RDS_DB_NAME}
      POSTGRES_USER: ${RDS_USERNAME}
      POSTGRES_PASSWORD: ${RDS_PASSWORD}
    ports:
      - "127.0.0.1:${RDS_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - dark_throne

networks:
  dark_throne:
    driver: bridge
